###############################################################################|
## Execute NONMEM Covariate Model via PsN --------------------------------------
###############################################################################|
##
## Description: This script executes a NONMEM population PK covariate model
## using the Perl speaks NONMEM (PsN) 'execute' utility. The script uses a
## custom wrapper function `psn_execute()` to call PsN from R.
##
## Note: This script requires NONMEM and PsN to be installed and accessible via
## the system PATH. The PsN execution function is designed to be compatible with
## both Windows and Unix systems (currently only tested on Windows OS). This
## step can be skipped if NONMEM or PsN are not installed or any other issues
## prevent successful execution of the script. Pre-generated model outputs
## (504.ext, 504.tab) included in this repo can still be used to run downstream 
## steps in the project workflow.
##
## Inputs:
##   - nm/cov/504.mod                     # NONMEM control stream (model file)
##
## Outputs (generated by NONMEM + PsN in "nm/cov/" directory):
##   - 504.lst                            # Model output listing
##   - 504.ext                            # Parameter estimates
##   - 504.tab                            # Output table with model predictions
##   - 504.phi                            # Individual ETAs
##   - 504.cov                            # Full covariance matrix
##   - 504.cor                            # Full correlation matrix
##   - 504.coi                            # Inverse covariance (i.e., Fisher information) matrix
##
###############################################################################|

###############################################################################|
## script setup ----------------------------------------------------------------
###############################################################################|

## specify R-script configuration ----------------------------------------------
mod_rela <- "nm/cov/504.mod"

### load dependent R packages --------------------------------------------------
pacman::p_load(dplyr, tidyr, tidylog)
crayon <- function(x) cat(crayon::magenta$bold(x), sep = "\n")
options("tidylog.display" = list(crayon))

### set project root directory & source custom R functions for analysis --------
withr::with_dir(this.path::this.dir(), {
  proj_root_pth <- usethis::proj_get()
  here::i_am(fs::path_rel(this.path::this.path(), start = proj_root_pth))
})
purrr::walk(list.files(here::here("R"), "(?i).*\\.R$", full.names = TRUE), source)

###############################################################################|
## specify file paths ----------------------------------------------------------
###############################################################################|


## expand relative path into absolute/full path
mod_path <- here::here(mod_rela) %>% print()
stopifnot(file.exists(mod_path))  ## verify file exists


###############################################################################|
## execute NONMEM model via PsN ------------------------------------------------
###############################################################################|


## call PsN execute via `psn_execute()` wrapper function (only works on Windows OS)
## NOTE:  `psn_execute()` currently only works on Windows OS
res <- psn_execute(
  mod_dir   = dirname(mod_path), 
  mod_files = basename(mod_path)
)


